apiVersion: apps/v1
kind: Deployment
metadata:
  name: planner-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planner-app
  template:
    metadata:
      labels:
        app: planner-app
    spec:
      containers:
      - name: planner-app
        image: sarthakrawat/studyaiy:__IMAGE_TAG__
        ports:
        - containerPort: 5000
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: groq-api-secret
              key: GROQ_API_KEY